name: CLARA
options:
  bundleIdPrefix: com.clara
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.2"

packages:
  swift-transformers:
    url: https://github.com/huggingface/swift-transformers
    from: "0.1.12"
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: "126.0.0"

targets:
  CLARA:
    type: application
    platform: iOS
    sources:
      - path: CLARA
        excludes:
          - "Resources/**"
      - path: CLARA/Resources/MedSigLIP_VisionEncoder.mlpackage
      - path: CLARA/Resources/MedSigLIP_TextEncoder.mlpackage
      - path: CLARA/Resources/tokenizer
        type: folder
        buildPhase: resources
      - path: CLARA/Resources/MedASR.mlpackage
      - path: CLARA/Resources/medasr_tokenizer
        type: folder
        buildPhase: resources
    dependencies:
      - package: swift-transformers
        product: Transformers
      - package: WebRTC
    info:
      path: CLARA/Info.plist
      properties:
        UILaunchScreen: {}
        NSCameraUsageDescription: "Take photos for classification"
        NSMicrophoneUsageDescription: "Stream audio during live sessions"
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    settings:
      base:
        SWIFT_VERSION: "5.9"
