name: CLARA
options:
  bundleIdPrefix: com.clara
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.2"

packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: "126.0.0"

targets:
  CLARA:
    type: application
    platform: iOS
    sources:
      - path: CLARA
        excludes:
          - "Resources/**"
          - "demo_files/**"
      - path: CLARA/Resources/MedSigLIP_VisionEncoder.mlpackage
      - path: CLARA/demo_files
        type: folder
        buildPhase: resources
    dependencies:
      - package: WebRTC
    info:
      path: CLARA/Info.plist
      properties:
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    settings:
      base:
        SWIFT_VERSION: "5.9"
